### ISSUE TITLE
Disappearing bones

### ISSUE THREAD

**Issue by dima-dencep** [tomalbrc/blockbench-import-library#1]
In blockbench, the model looks like this:
![image](https://github.com/user-attachments/assets/660e19e8-129a-40af-8ed6-617222dab0df)

However, one bone was lost in the game:
![image](https://github.com/user-attachments/assets/7635f8b9-ffbb-4362-b53e-3332f394dc74)

**Comment by shizotoaster** [comment]
Here's the model in question (gh doesn't allow .bbmodel attachments so I renamed it to .bbmodel.txt) [stabilizer.bbmodel.txt](https://github.com/user-attachments/files/16870915/stabilizer.bbmodel.txt)

**Comment by tomalbrc** [comment]
It is overwriting the inner octagon bone its model :P
For now the easy workaround is to rename the bone in block bench, but the bug will be fixed soon with 1.1.13 sometime this or next week
![image](https://github.com/user-attachments/assets/ef14526e-1693-45be-b612-66f3a3a91135)

**Comment by shizotoaster** [comment]
Amazing, thank you!

**Comment by tomalbrc** [comment]
this was fixed in 1.1.13
